/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as StreetScanRouteImport } from './routes/street-scan'
import { Route as StartRouteImport } from './routes/start'
import { Route as SolarRouteImport } from './routes/solar'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RealestateRouteImport } from './routes/realestate'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MortgageRouteImport } from './routes/mortgage'
import { Route as MedicalRouteImport } from './routes/medical'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HomeServicesRouteImport } from './routes/home-services'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EducationRouteImport } from './routes/education'
import { Route as EcommerceRouteImport } from './routes/ecommerce'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AutoRouteImport } from './routes/auto'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiDrivingForDollarsRouteImport } from './routes/ai-driving-for-dollars'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as DistressFeedIndexRouteImport } from './routes/distress-feed.index'
import { Route as ToolsLineTypeCheckerRouteImport } from './routes/tools.line-type-checker'
import { Route as ToolsDncCheckerRouteImport } from './routes/tools.dnc-checker'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates.$templateId'
import { Route as LeadsSlugRouteImport } from './routes/leads.$slug'
import { Route as AuthHubRouteImport } from './routes/auth.hub'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as DistressFeedGuidesIndexRouteImport } from './routes/distress-feed.guides.index'
import { Route as DistressFeedCountiesIndexRouteImport } from './routes/distress-feed.counties.index'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedPlatformWorkspacesRouteImport } from './routes/_authenticated/platform.workspaces'
import { Route as AuthenticatedPlatformSourcesRouteImport } from './routes/_authenticated/platform.sources'
import { Route as AuthenticatedPlatformSequencesRouteImport } from './routes/_authenticated/platform.sequences'
import { Route as AuthenticatedPlatformRecordsRouteImport } from './routes/_authenticated/platform.records'
import { Route as AuthenticatedPlatformAccessRouteImport } from './routes/_authenticated/platform.access'
import { Route as AuthenticatedAppWorkspaceRouteImport } from './routes/_authenticated/app.workspace'
import { Route as AuthenticatedAppTemplatesRouteImport } from './routes/_authenticated/app.templates'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app.reports'
import { Route as AuthenticatedAppRegistrationRouteImport } from './routes/_authenticated/app.registration'
import { Route as AuthenticatedAppPropertySearchRouteImport } from './routes/_authenticated/app.property-search'
import { Route as AuthenticatedAppNumbersRouteImport } from './routes/_authenticated/app.numbers'
import { Route as AuthenticatedAppLeadsRouteImport } from './routes/_authenticated/app.leads'
import { Route as AuthenticatedAppIntegrationsRouteImport } from './routes/_authenticated/app.integrations'
import { Route as AuthenticatedAppInboxRouteImport } from './routes/_authenticated/app.inbox'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppComplianceRouteImport } from './routes/_authenticated/app.compliance'
import { Route as AuthenticatedAppBrandsRouteImport } from './routes/_authenticated/app.brands'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppAssistantRouteImport } from './routes/_authenticated/app.assistant'
import { Route as AuthenticatedAppApiRouteImport } from './routes/_authenticated/app.api'
import { Route as AuthenticatedAppAgentRouteImport } from './routes/_authenticated/app.agent'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app.account'
import { Route as DistressFeedGuidesStateIndexRouteImport } from './routes/distress-feed.guides.$state.index'
import { Route as DistressFeedCountiesStateIndexRouteImport } from './routes/distress-feed.counties.$state.index'
import { Route as AuthenticatedAppNewListIndexRouteImport } from './routes/_authenticated/app.new-list.index'
import { Route as AuthenticatedAppNewJobIndexRouteImport } from './routes/_authenticated/app.new-job.index'
import { Route as AuthenticatedAppListsIndexRouteImport } from './routes/_authenticated/app.lists.index'
import { Route as AuthenticatedAppJobsIndexRouteImport } from './routes/_authenticated/app.jobs.index'
import { Route as AuthenticatedAppCampaignsIndexRouteImport } from './routes/_authenticated/app.campaigns.index'
import { Route as DistressFeedCountiesStateCountyRouteImport } from './routes/distress-feed.counties.$state.$county'
import { Route as ApiPublicV1LeadsRouteImport } from './routes/api/public/v1/leads'
import { Route as ApiPublicV1JobsRouteImport } from './routes/api/public/v1/jobs'
import { Route as ApiPublicV1CampaignsRouteImport } from './routes/api/public/v1/campaigns'
import { Route as ApiPublicHubCallbackRouteImport } from './routes/api/public/hub/callback'
import { Route as ApiPublicHooksTickTemplateHealthRouteImport } from './routes/api/public/hooks/tick-template-health'
import { Route as ApiPublicHooksTickSequencesRouteImport } from './routes/api/public/hooks/tick-sequences'
import { Route as ApiPublicHooksTickRegistrationsRouteImport } from './routes/api/public/hooks/tick-registrations'
import { Route as ApiPublicHooksTickRecordsRequestsRouteImport } from './routes/api/public/hooks/tick-records-requests'
import { Route as ApiPublicHooksTickRealeflowSourcingRouteImport } from './routes/api/public/hooks/tick-realeflow-sourcing'
import { Route as ApiPublicHooksTickJobsRouteImport } from './routes/api/public/hooks/tick-jobs'
import { Route as ApiPublicHooksTickDistressFeedRouteImport } from './routes/api/public/hooks/tick-distress-feed'
import { Route as ApiPublicHooksTickCampaignsRouteImport } from './routes/api/public/hooks/tick-campaigns'
import { Route as ApiPublicHooksTelnyxInboundRouteImport } from './routes/api/public/hooks/telnyx-inbound'
import { Route as ApiPublicHooksTelnyxDlrRouteImport } from './routes/api/public/hooks/telnyx-dlr'
import { Route as ApiPublicHooksTelnyxCallRouteImport } from './routes/api/public/hooks/telnyx-call'
import { Route as ApiPublicHooksRecordsInboundRouteImport } from './routes/api/public/hooks/records-inbound'
import { Route as AuthenticatedAppNewListSplatRouteImport } from './routes/_authenticated/app.new-list.$'
import { Route as AuthenticatedAppNewJobSplatRouteImport } from './routes/_authenticated/app.new-job.$'
import { Route as AuthenticatedAppListsListIdRouteImport } from './routes/_authenticated/app.lists.$listId'
import { Route as AuthenticatedAppJobsSplatRouteImport } from './routes/_authenticated/app.jobs.$'
import { Route as AuthenticatedAppCampaignsNewRouteImport } from './routes/_authenticated/app.campaigns.new'
import { Route as AuthenticatedAppCampaignsCampaignIdRouteImport } from './routes/_authenticated/app.campaigns.$campaignId'
import { Route as DistressFeedGuidesStateCountyRecordTypeRouteImport } from './routes/distress-feed.guides.$state.$county.$recordType'
import { Route as ApiPublicV1JobsJobIdRouteImport } from './routes/api/public/v1/jobs.$jobId'

const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const StreetScanRoute = StreetScanRouteImport.update({
  id: '/street-scan',
  path: '/street-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarRoute = SolarRouteImport.update({
  id: '/solar',
  path: '/solar',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RealestateRoute = RealestateRouteImport.update({
  id: '/realestate',
  path: '/realestate',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageRoute = MortgageRouteImport.update({
  id: '/mortgage',
  path: '/mortgage',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRoute = MedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeServicesRoute = HomeServicesRouteImport.update({
  id: '/home-services',
  path: '/home-services',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoRoute = AutoRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDrivingForDollarsRoute = AiDrivingForDollarsRouteImport.update({
  id: '/ai-driving-for-dollars',
  path: '/ai-driving-for-dollars',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistressFeedIndexRoute = DistressFeedIndexRouteImport.update({
  id: '/distress-feed/',
  path: '/distress-feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLineTypeCheckerRoute = ToolsLineTypeCheckerRouteImport.update({
  id: '/tools/line-type-checker',
  path: '/tools/line-type-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDncCheckerRoute = ToolsDncCheckerRouteImport.update({
  id: '/tools/dnc-checker',
  path: '/tools/dnc-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsSlugRoute = LeadsSlugRouteImport.update({
  id: '/leads/$slug',
  path: '/leads/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHubRoute = AuthHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DistressFeedGuidesIndexRoute = DistressFeedGuidesIndexRouteImport.update({
  id: '/distress-feed/guides/',
  path: '/distress-feed/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistressFeedCountiesIndexRoute =
  DistressFeedCountiesIndexRouteImport.update({
    id: '/distress-feed/counties/',
    path: '/distress-feed/counties/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedPlatformWorkspacesRoute =
  AuthenticatedPlatformWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformSourcesRoute =
  AuthenticatedPlatformSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformSequencesRoute =
  AuthenticatedPlatformSequencesRouteImport.update({
    id: '/sequences',
    path: '/sequences',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformRecordsRoute =
  AuthenticatedPlatformRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformAccessRoute =
  AuthenticatedPlatformAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedAppWorkspaceRoute =
  AuthenticatedAppWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTemplatesRoute =
  AuthenticatedAppTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRegistrationRoute =
  AuthenticatedAppRegistrationRouteImport.update({
    id: '/registration',
    path: '/registration',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPropertySearchRoute =
  AuthenticatedAppPropertySearchRouteImport.update({
    id: '/property-search',
    path: '/property-search',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNumbersRoute = AuthenticatedAppNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLeadsRoute = AuthenticatedAppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppIntegrationsRoute =
  AuthenticatedAppIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInboxRoute = AuthenticatedAppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComplianceRoute =
  AuthenticatedAppComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBrandsRoute = AuthenticatedAppBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAssistantRoute =
  AuthenticatedAppAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppApiRoute = AuthenticatedAppApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgentRoute = AuthenticatedAppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const DistressFeedGuidesStateIndexRoute =
  DistressFeedGuidesStateIndexRouteImport.update({
    id: '/distress-feed/guides/$state/',
    path: '/distress-feed/guides/$state/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DistressFeedCountiesStateIndexRoute =
  DistressFeedCountiesStateIndexRouteImport.update({
    id: '/distress-feed/counties/$state/',
    path: '/distress-feed/counties/$state/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppNewListIndexRoute =
  AuthenticatedAppNewListIndexRouteImport.update({
    id: '/new-list/',
    path: '/new-list/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNewJobIndexRoute =
  AuthenticatedAppNewJobIndexRouteImport.update({
    id: '/new-job/',
    path: '/new-job/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppListsIndexRoute =
  AuthenticatedAppListsIndexRouteImport.update({
    id: '/lists/',
    path: '/lists/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppJobsIndexRoute =
  AuthenticatedAppJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsIndexRoute =
  AuthenticatedAppCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const DistressFeedCountiesStateCountyRoute =
  DistressFeedCountiesStateCountyRouteImport.update({
    id: '/distress-feed/counties/$state/$county',
    path: '/distress-feed/counties/$state/$county',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1LeadsRoute = ApiPublicV1LeadsRouteImport.update({
  id: '/api/public/v1/leads',
  path: '/api/public/v1/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1JobsRoute = ApiPublicV1JobsRouteImport.update({
  id: '/api/public/v1/jobs',
  path: '/api/public/v1/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CampaignsRoute = ApiPublicV1CampaignsRouteImport.update({
  id: '/api/public/v1/campaigns',
  path: '/api/public/v1/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHubCallbackRoute = ApiPublicHubCallbackRouteImport.update({
  id: '/api/public/hub/callback',
  path: '/api/public/hub/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTickTemplateHealthRoute =
  ApiPublicHooksTickTemplateHealthRouteImport.update({
    id: '/api/public/hooks/tick-template-health',
    path: '/api/public/hooks/tick-template-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTickSequencesRoute =
  ApiPublicHooksTickSequencesRouteImport.update({
    id: '/api/public/hooks/tick-sequences',
    path: '/api/public/hooks/tick-sequences',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTickRegistrationsRoute =
  ApiPublicHooksTickRegistrationsRouteImport.update({
    id: '/api/public/hooks/tick-registrations',
    path: '/api/public/hooks/tick-registrations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTickRecordsRequestsRoute =
  ApiPublicHooksTickRecordsRequestsRouteImport.update({
    id: '/api/public/hooks/tick-records-requests',
    path: '/api/public/hooks/tick-records-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTickRealeflowSourcingRoute =
  ApiPublicHooksTickRealeflowSourcingRouteImport.update({
    id: '/api/public/hooks/tick-realeflow-sourcing',
    path: '/api/public/hooks/tick-realeflow-sourcing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTickJobsRoute = ApiPublicHooksTickJobsRouteImport.update({
  id: '/api/public/hooks/tick-jobs',
  path: '/api/public/hooks/tick-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTickDistressFeedRoute =
  ApiPublicHooksTickDistressFeedRouteImport.update({
    id: '/api/public/hooks/tick-distress-feed',
    path: '/api/public/hooks/tick-distress-feed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTickCampaignsRoute =
  ApiPublicHooksTickCampaignsRouteImport.update({
    id: '/api/public/hooks/tick-campaigns',
    path: '/api/public/hooks/tick-campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelnyxInboundRoute =
  ApiPublicHooksTelnyxInboundRouteImport.update({
    id: '/api/public/hooks/telnyx-inbound',
    path: '/api/public/hooks/telnyx-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelnyxDlrRoute = ApiPublicHooksTelnyxDlrRouteImport.update({
  id: '/api/public/hooks/telnyx-dlr',
  path: '/api/public/hooks/telnyx-dlr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTelnyxCallRoute =
  ApiPublicHooksTelnyxCallRouteImport.update({
    id: '/api/public/hooks/telnyx-call',
    path: '/api/public/hooks/telnyx-call',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecordsInboundRoute =
  ApiPublicHooksRecordsInboundRouteImport.update({
    id: '/api/public/hooks/records-inbound',
    path: '/api/public/hooks/records-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppNewListSplatRoute =
  AuthenticatedAppNewListSplatRouteImport.update({
    id: '/new-list/$',
    path: '/new-list/$',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNewJobSplatRoute =
  AuthenticatedAppNewJobSplatRouteImport.update({
    id: '/new-job/$',
    path: '/new-job/$',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppListsListIdRoute =
  AuthenticatedAppListsListIdRouteImport.update({
    id: '/lists/$listId',
    path: '/lists/$listId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppJobsSplatRoute =
  AuthenticatedAppJobsSplatRouteImport.update({
    id: '/jobs/$',
    path: '/jobs/$',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsNewRoute =
  AuthenticatedAppCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsCampaignIdRoute =
  AuthenticatedAppCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const DistressFeedGuidesStateCountyRecordTypeRoute =
  DistressFeedGuidesStateCountyRecordTypeRouteImport.update({
    id: '/distress-feed/guides/$state/$county/$recordType',
    path: '/distress-feed/guides/$state/$county/$recordType',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1JobsJobIdRoute = ApiPublicV1JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiPublicV1JobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/agency': typeof AgencyRoute
  '/ai-driving-for-dollars': typeof AiDrivingForDollarsRoute
  '/auth': typeof AuthRouteWithChildren
  '/auto': typeof AutoRoute
  '/b2b': typeof B2bRoute
  '/compliance': typeof ComplianceRoute
  '/ecommerce': typeof EcommerceRoute
  '/education': typeof EducationRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/home-services': typeof HomeServicesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/insurance': typeof InsuranceRoute
  '/legal': typeof LegalRoute
  '/medical': typeof MedicalRoute
  '/mortgage': typeof MortgageRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/realestate': typeof RealestateRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/start': typeof StartRoute
  '/street-scan': typeof StreetScanRoute
  '/tutorials': typeof TutorialsRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/auth/hub': typeof AuthHubRoute
  '/leads/$slug': typeof LeadsSlugRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/tools/dnc-checker': typeof ToolsDncCheckerRoute
  '/tools/line-type-checker': typeof ToolsLineTypeCheckerRoute
  '/distress-feed/': typeof DistressFeedIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/agent': typeof AuthenticatedAppAgentRoute
  '/app/api': typeof AuthenticatedAppApiRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/brands': typeof AuthenticatedAppBrandsRoute
  '/app/compliance': typeof AuthenticatedAppComplianceRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/numbers': typeof AuthenticatedAppNumbersRoute
  '/app/property-search': typeof AuthenticatedAppPropertySearchRoute
  '/app/registration': typeof AuthenticatedAppRegistrationRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/workspace': typeof AuthenticatedAppWorkspaceRoute
  '/platform/access': typeof AuthenticatedPlatformAccessRoute
  '/platform/records': typeof AuthenticatedPlatformRecordsRoute
  '/platform/sequences': typeof AuthenticatedPlatformSequencesRoute
  '/platform/sources': typeof AuthenticatedPlatformSourcesRoute
  '/platform/workspaces': typeof AuthenticatedPlatformWorkspacesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
  '/distress-feed/counties/': typeof DistressFeedCountiesIndexRoute
  '/distress-feed/guides/': typeof DistressFeedGuidesIndexRoute
  '/app/campaigns/$campaignId': typeof AuthenticatedAppCampaignsCampaignIdRoute
  '/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/app/jobs/$': typeof AuthenticatedAppJobsSplatRoute
  '/app/lists/$listId': typeof AuthenticatedAppListsListIdRoute
  '/app/new-job/$': typeof AuthenticatedAppNewJobSplatRoute
  '/app/new-list/$': typeof AuthenticatedAppNewListSplatRoute
  '/api/public/hooks/records-inbound': typeof ApiPublicHooksRecordsInboundRoute
  '/api/public/hooks/telnyx-call': typeof ApiPublicHooksTelnyxCallRoute
  '/api/public/hooks/telnyx-dlr': typeof ApiPublicHooksTelnyxDlrRoute
  '/api/public/hooks/telnyx-inbound': typeof ApiPublicHooksTelnyxInboundRoute
  '/api/public/hooks/tick-campaigns': typeof ApiPublicHooksTickCampaignsRoute
  '/api/public/hooks/tick-distress-feed': typeof ApiPublicHooksTickDistressFeedRoute
  '/api/public/hooks/tick-jobs': typeof ApiPublicHooksTickJobsRoute
  '/api/public/hooks/tick-realeflow-sourcing': typeof ApiPublicHooksTickRealeflowSourcingRoute
  '/api/public/hooks/tick-records-requests': typeof ApiPublicHooksTickRecordsRequestsRoute
  '/api/public/hooks/tick-registrations': typeof ApiPublicHooksTickRegistrationsRoute
  '/api/public/hooks/tick-sequences': typeof ApiPublicHooksTickSequencesRoute
  '/api/public/hooks/tick-template-health': typeof ApiPublicHooksTickTemplateHealthRoute
  '/api/public/hub/callback': typeof ApiPublicHubCallbackRoute
  '/api/public/v1/campaigns': typeof ApiPublicV1CampaignsRoute
  '/api/public/v1/jobs': typeof ApiPublicV1JobsRouteWithChildren
  '/api/public/v1/leads': typeof ApiPublicV1LeadsRoute
  '/distress-feed/counties/$state/$county': typeof DistressFeedCountiesStateCountyRoute
  '/app/campaigns/': typeof AuthenticatedAppCampaignsIndexRoute
  '/app/jobs/': typeof AuthenticatedAppJobsIndexRoute
  '/app/lists/': typeof AuthenticatedAppListsIndexRoute
  '/app/new-job/': typeof AuthenticatedAppNewJobIndexRoute
  '/app/new-list/': typeof AuthenticatedAppNewListIndexRoute
  '/distress-feed/counties/$state/': typeof DistressFeedCountiesStateIndexRoute
  '/distress-feed/guides/$state/': typeof DistressFeedGuidesStateIndexRoute
  '/api/public/v1/jobs/$jobId': typeof ApiPublicV1JobsJobIdRoute
  '/distress-feed/guides/$state/$county/$recordType': typeof DistressFeedGuidesStateCountyRecordTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/agency': typeof AgencyRoute
  '/ai-driving-for-dollars': typeof AiDrivingForDollarsRoute
  '/auth': typeof AuthRouteWithChildren
  '/auto': typeof AutoRoute
  '/b2b': typeof B2bRoute
  '/compliance': typeof ComplianceRoute
  '/ecommerce': typeof EcommerceRoute
  '/education': typeof EducationRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/home-services': typeof HomeServicesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/insurance': typeof InsuranceRoute
  '/legal': typeof LegalRoute
  '/medical': typeof MedicalRoute
  '/mortgage': typeof MortgageRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/realestate': typeof RealestateRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/start': typeof StartRoute
  '/street-scan': typeof StreetScanRoute
  '/tutorials': typeof TutorialsRoute
  '/auth/hub': typeof AuthHubRoute
  '/leads/$slug': typeof LeadsSlugRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/tools/dnc-checker': typeof ToolsDncCheckerRoute
  '/tools/line-type-checker': typeof ToolsLineTypeCheckerRoute
  '/distress-feed': typeof DistressFeedIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/agent': typeof AuthenticatedAppAgentRoute
  '/app/api': typeof AuthenticatedAppApiRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/brands': typeof AuthenticatedAppBrandsRoute
  '/app/compliance': typeof AuthenticatedAppComplianceRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/numbers': typeof AuthenticatedAppNumbersRoute
  '/app/property-search': typeof AuthenticatedAppPropertySearchRoute
  '/app/registration': typeof AuthenticatedAppRegistrationRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/workspace': typeof AuthenticatedAppWorkspaceRoute
  '/platform/access': typeof AuthenticatedPlatformAccessRoute
  '/platform/records': typeof AuthenticatedPlatformRecordsRoute
  '/platform/sequences': typeof AuthenticatedPlatformSequencesRoute
  '/platform/sources': typeof AuthenticatedPlatformSourcesRoute
  '/platform/workspaces': typeof AuthenticatedPlatformWorkspacesRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
  '/distress-feed/counties': typeof DistressFeedCountiesIndexRoute
  '/distress-feed/guides': typeof DistressFeedGuidesIndexRoute
  '/app/campaigns/$campaignId': typeof AuthenticatedAppCampaignsCampaignIdRoute
  '/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/app/jobs/$': typeof AuthenticatedAppJobsSplatRoute
  '/app/lists/$listId': typeof AuthenticatedAppListsListIdRoute
  '/app/new-job/$': typeof AuthenticatedAppNewJobSplatRoute
  '/app/new-list/$': typeof AuthenticatedAppNewListSplatRoute
  '/api/public/hooks/records-inbound': typeof ApiPublicHooksRecordsInboundRoute
  '/api/public/hooks/telnyx-call': typeof ApiPublicHooksTelnyxCallRoute
  '/api/public/hooks/telnyx-dlr': typeof ApiPublicHooksTelnyxDlrRoute
  '/api/public/hooks/telnyx-inbound': typeof ApiPublicHooksTelnyxInboundRoute
  '/api/public/hooks/tick-campaigns': typeof ApiPublicHooksTickCampaignsRoute
  '/api/public/hooks/tick-distress-feed': typeof ApiPublicHooksTickDistressFeedRoute
  '/api/public/hooks/tick-jobs': typeof ApiPublicHooksTickJobsRoute
  '/api/public/hooks/tick-realeflow-sourcing': typeof ApiPublicHooksTickRealeflowSourcingRoute
  '/api/public/hooks/tick-records-requests': typeof ApiPublicHooksTickRecordsRequestsRoute
  '/api/public/hooks/tick-registrations': typeof ApiPublicHooksTickRegistrationsRoute
  '/api/public/hooks/tick-sequences': typeof ApiPublicHooksTickSequencesRoute
  '/api/public/hooks/tick-template-health': typeof ApiPublicHooksTickTemplateHealthRoute
  '/api/public/hub/callback': typeof ApiPublicHubCallbackRoute
  '/api/public/v1/campaigns': typeof ApiPublicV1CampaignsRoute
  '/api/public/v1/jobs': typeof ApiPublicV1JobsRouteWithChildren
  '/api/public/v1/leads': typeof ApiPublicV1LeadsRoute
  '/distress-feed/counties/$state/$county': typeof DistressFeedCountiesStateCountyRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsIndexRoute
  '/app/jobs': typeof AuthenticatedAppJobsIndexRoute
  '/app/lists': typeof AuthenticatedAppListsIndexRoute
  '/app/new-job': typeof AuthenticatedAppNewJobIndexRoute
  '/app/new-list': typeof AuthenticatedAppNewListIndexRoute
  '/distress-feed/counties/$state': typeof DistressFeedCountiesStateIndexRoute
  '/distress-feed/guides/$state': typeof DistressFeedGuidesStateIndexRoute
  '/api/public/v1/jobs/$jobId': typeof ApiPublicV1JobsJobIdRoute
  '/distress-feed/guides/$state/$county/$recordType': typeof DistressFeedGuidesStateCountyRecordTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/agency': typeof AgencyRoute
  '/ai-driving-for-dollars': typeof AiDrivingForDollarsRoute
  '/auth': typeof AuthRouteWithChildren
  '/auto': typeof AutoRoute
  '/b2b': typeof B2bRoute
  '/compliance': typeof ComplianceRoute
  '/ecommerce': typeof EcommerceRoute
  '/education': typeof EducationRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/home-services': typeof HomeServicesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/insurance': typeof InsuranceRoute
  '/legal': typeof LegalRoute
  '/medical': typeof MedicalRoute
  '/mortgage': typeof MortgageRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/realestate': typeof RealestateRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/start': typeof StartRoute
  '/street-scan': typeof StreetScanRoute
  '/tutorials': typeof TutorialsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/auth/hub': typeof AuthHubRoute
  '/leads/$slug': typeof LeadsSlugRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/tools/dnc-checker': typeof ToolsDncCheckerRoute
  '/tools/line-type-checker': typeof ToolsLineTypeCheckerRoute
  '/distress-feed/': typeof DistressFeedIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/agent': typeof AuthenticatedAppAgentRoute
  '/_authenticated/app/api': typeof AuthenticatedAppApiRoute
  '/_authenticated/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/brands': typeof AuthenticatedAppBrandsRoute
  '/_authenticated/app/compliance': typeof AuthenticatedAppComplianceRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/inbox': typeof AuthenticatedAppInboxRoute
  '/_authenticated/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/_authenticated/app/leads': typeof AuthenticatedAppLeadsRoute
  '/_authenticated/app/numbers': typeof AuthenticatedAppNumbersRoute
  '/_authenticated/app/property-search': typeof AuthenticatedAppPropertySearchRoute
  '/_authenticated/app/registration': typeof AuthenticatedAppRegistrationRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/_authenticated/app/workspace': typeof AuthenticatedAppWorkspaceRoute
  '/_authenticated/platform/access': typeof AuthenticatedPlatformAccessRoute
  '/_authenticated/platform/records': typeof AuthenticatedPlatformRecordsRoute
  '/_authenticated/platform/sequences': typeof AuthenticatedPlatformSequencesRoute
  '/_authenticated/platform/sources': typeof AuthenticatedPlatformSourcesRoute
  '/_authenticated/platform/workspaces': typeof AuthenticatedPlatformWorkspacesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
  '/distress-feed/counties/': typeof DistressFeedCountiesIndexRoute
  '/distress-feed/guides/': typeof DistressFeedGuidesIndexRoute
  '/_authenticated/app/campaigns/$campaignId': typeof AuthenticatedAppCampaignsCampaignIdRoute
  '/_authenticated/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/_authenticated/app/jobs/$': typeof AuthenticatedAppJobsSplatRoute
  '/_authenticated/app/lists/$listId': typeof AuthenticatedAppListsListIdRoute
  '/_authenticated/app/new-job/$': typeof AuthenticatedAppNewJobSplatRoute
  '/_authenticated/app/new-list/$': typeof AuthenticatedAppNewListSplatRoute
  '/api/public/hooks/records-inbound': typeof ApiPublicHooksRecordsInboundRoute
  '/api/public/hooks/telnyx-call': typeof ApiPublicHooksTelnyxCallRoute
  '/api/public/hooks/telnyx-dlr': typeof ApiPublicHooksTelnyxDlrRoute
  '/api/public/hooks/telnyx-inbound': typeof ApiPublicHooksTelnyxInboundRoute
  '/api/public/hooks/tick-campaigns': typeof ApiPublicHooksTickCampaignsRoute
  '/api/public/hooks/tick-distress-feed': typeof ApiPublicHooksTickDistressFeedRoute
  '/api/public/hooks/tick-jobs': typeof ApiPublicHooksTickJobsRoute
  '/api/public/hooks/tick-realeflow-sourcing': typeof ApiPublicHooksTickRealeflowSourcingRoute
  '/api/public/hooks/tick-records-requests': typeof ApiPublicHooksTickRecordsRequestsRoute
  '/api/public/hooks/tick-registrations': typeof ApiPublicHooksTickRegistrationsRoute
  '/api/public/hooks/tick-sequences': typeof ApiPublicHooksTickSequencesRoute
  '/api/public/hooks/tick-template-health': typeof ApiPublicHooksTickTemplateHealthRoute
  '/api/public/hub/callback': typeof ApiPublicHubCallbackRoute
  '/api/public/v1/campaigns': typeof ApiPublicV1CampaignsRoute
  '/api/public/v1/jobs': typeof ApiPublicV1JobsRouteWithChildren
  '/api/public/v1/leads': typeof ApiPublicV1LeadsRoute
  '/distress-feed/counties/$state/$county': typeof DistressFeedCountiesStateCountyRoute
  '/_authenticated/app/campaigns/': typeof AuthenticatedAppCampaignsIndexRoute
  '/_authenticated/app/jobs/': typeof AuthenticatedAppJobsIndexRoute
  '/_authenticated/app/lists/': typeof AuthenticatedAppListsIndexRoute
  '/_authenticated/app/new-job/': typeof AuthenticatedAppNewJobIndexRoute
  '/_authenticated/app/new-list/': typeof AuthenticatedAppNewListIndexRoute
  '/distress-feed/counties/$state/': typeof DistressFeedCountiesStateIndexRoute
  '/distress-feed/guides/$state/': typeof DistressFeedGuidesStateIndexRoute
  '/api/public/v1/jobs/$jobId': typeof ApiPublicV1JobsJobIdRoute
  '/distress-feed/guides/$state/$county/$recordType': typeof DistressFeedGuidesStateCountyRecordTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/agency'
    | '/ai-driving-for-dollars'
    | '/auth'
    | '/auto'
    | '/b2b'
    | '/compliance'
    | '/ecommerce'
    | '/education'
    | '/features'
    | '/help'
    | '/home-services'
    | '/how-it-works'
    | '/industries'
    | '/insurance'
    | '/legal'
    | '/medical'
    | '/mortgage'
    | '/onboarding'
    | '/pricing'
    | '/realestate'
    | '/reset-password'
    | '/sign-in'
    | '/sitemap.xml'
    | '/solar'
    | '/start'
    | '/street-scan'
    | '/tutorials'
    | '/app'
    | '/platform'
    | '/auth/hub'
    | '/leads/$slug'
    | '/templates/$templateId'
    | '/tools/dnc-checker'
    | '/tools/line-type-checker'
    | '/distress-feed/'
    | '/leads/'
    | '/templates/'
    | '/tools/'
    | '/app/account'
    | '/app/agent'
    | '/app/api'
    | '/app/assistant'
    | '/app/billing'
    | '/app/brands'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/inbox'
    | '/app/integrations'
    | '/app/leads'
    | '/app/numbers'
    | '/app/property-search'
    | '/app/registration'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/templates'
    | '/app/workspace'
    | '/platform/access'
    | '/platform/records'
    | '/platform/sequences'
    | '/platform/sources'
    | '/platform/workspaces'
    | '/app/'
    | '/platform/'
    | '/distress-feed/counties/'
    | '/distress-feed/guides/'
    | '/app/campaigns/$campaignId'
    | '/app/campaigns/new'
    | '/app/jobs/$'
    | '/app/lists/$listId'
    | '/app/new-job/$'
    | '/app/new-list/$'
    | '/api/public/hooks/records-inbound'
    | '/api/public/hooks/telnyx-call'
    | '/api/public/hooks/telnyx-dlr'
    | '/api/public/hooks/telnyx-inbound'
    | '/api/public/hooks/tick-campaigns'
    | '/api/public/hooks/tick-distress-feed'
    | '/api/public/hooks/tick-jobs'
    | '/api/public/hooks/tick-realeflow-sourcing'
    | '/api/public/hooks/tick-records-requests'
    | '/api/public/hooks/tick-registrations'
    | '/api/public/hooks/tick-sequences'
    | '/api/public/hooks/tick-template-health'
    | '/api/public/hub/callback'
    | '/api/public/v1/campaigns'
    | '/api/public/v1/jobs'
    | '/api/public/v1/leads'
    | '/distress-feed/counties/$state/$county'
    | '/app/campaigns/'
    | '/app/jobs/'
    | '/app/lists/'
    | '/app/new-job/'
    | '/app/new-list/'
    | '/distress-feed/counties/$state/'
    | '/distress-feed/guides/$state/'
    | '/api/public/v1/jobs/$jobId'
    | '/distress-feed/guides/$state/$county/$recordType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/agency'
    | '/ai-driving-for-dollars'
    | '/auth'
    | '/auto'
    | '/b2b'
    | '/compliance'
    | '/ecommerce'
    | '/education'
    | '/features'
    | '/help'
    | '/home-services'
    | '/how-it-works'
    | '/industries'
    | '/insurance'
    | '/legal'
    | '/medical'
    | '/mortgage'
    | '/onboarding'
    | '/pricing'
    | '/realestate'
    | '/reset-password'
    | '/sign-in'
    | '/sitemap.xml'
    | '/solar'
    | '/start'
    | '/street-scan'
    | '/tutorials'
    | '/auth/hub'
    | '/leads/$slug'
    | '/templates/$templateId'
    | '/tools/dnc-checker'
    | '/tools/line-type-checker'
    | '/distress-feed'
    | '/leads'
    | '/templates'
    | '/tools'
    | '/app/account'
    | '/app/agent'
    | '/app/api'
    | '/app/assistant'
    | '/app/billing'
    | '/app/brands'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/inbox'
    | '/app/integrations'
    | '/app/leads'
    | '/app/numbers'
    | '/app/property-search'
    | '/app/registration'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/templates'
    | '/app/workspace'
    | '/platform/access'
    | '/platform/records'
    | '/platform/sequences'
    | '/platform/sources'
    | '/platform/workspaces'
    | '/app'
    | '/platform'
    | '/distress-feed/counties'
    | '/distress-feed/guides'
    | '/app/campaigns/$campaignId'
    | '/app/campaigns/new'
    | '/app/jobs/$'
    | '/app/lists/$listId'
    | '/app/new-job/$'
    | '/app/new-list/$'
    | '/api/public/hooks/records-inbound'
    | '/api/public/hooks/telnyx-call'
    | '/api/public/hooks/telnyx-dlr'
    | '/api/public/hooks/telnyx-inbound'
    | '/api/public/hooks/tick-campaigns'
    | '/api/public/hooks/tick-distress-feed'
    | '/api/public/hooks/tick-jobs'
    | '/api/public/hooks/tick-realeflow-sourcing'
    | '/api/public/hooks/tick-records-requests'
    | '/api/public/hooks/tick-registrations'
    | '/api/public/hooks/tick-sequences'
    | '/api/public/hooks/tick-template-health'
    | '/api/public/hub/callback'
    | '/api/public/v1/campaigns'
    | '/api/public/v1/jobs'
    | '/api/public/v1/leads'
    | '/distress-feed/counties/$state/$county'
    | '/app/campaigns'
    | '/app/jobs'
    | '/app/lists'
    | '/app/new-job'
    | '/app/new-list'
    | '/distress-feed/counties/$state'
    | '/distress-feed/guides/$state'
    | '/api/public/v1/jobs/$jobId'
    | '/distress-feed/guides/$state/$county/$recordType'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/agency'
    | '/ai-driving-for-dollars'
    | '/auth'
    | '/auto'
    | '/b2b'
    | '/compliance'
    | '/ecommerce'
    | '/education'
    | '/features'
    | '/help'
    | '/home-services'
    | '/how-it-works'
    | '/industries'
    | '/insurance'
    | '/legal'
    | '/medical'
    | '/mortgage'
    | '/onboarding'
    | '/pricing'
    | '/realestate'
    | '/reset-password'
    | '/sign-in'
    | '/sitemap.xml'
    | '/solar'
    | '/start'
    | '/street-scan'
    | '/tutorials'
    | '/_authenticated/app'
    | '/_authenticated/platform'
    | '/auth/hub'
    | '/leads/$slug'
    | '/templates/$templateId'
    | '/tools/dnc-checker'
    | '/tools/line-type-checker'
    | '/distress-feed/'
    | '/leads/'
    | '/templates/'
    | '/tools/'
    | '/_authenticated/app/account'
    | '/_authenticated/app/agent'
    | '/_authenticated/app/api'
    | '/_authenticated/app/assistant'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/brands'
    | '/_authenticated/app/compliance'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/inbox'
    | '/_authenticated/app/integrations'
    | '/_authenticated/app/leads'
    | '/_authenticated/app/numbers'
    | '/_authenticated/app/property-search'
    | '/_authenticated/app/registration'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/team'
    | '/_authenticated/app/templates'
    | '/_authenticated/app/workspace'
    | '/_authenticated/platform/access'
    | '/_authenticated/platform/records'
    | '/_authenticated/platform/sequences'
    | '/_authenticated/platform/sources'
    | '/_authenticated/platform/workspaces'
    | '/_authenticated/app/'
    | '/_authenticated/platform/'
    | '/distress-feed/counties/'
    | '/distress-feed/guides/'
    | '/_authenticated/app/campaigns/$campaignId'
    | '/_authenticated/app/campaigns/new'
    | '/_authenticated/app/jobs/$'
    | '/_authenticated/app/lists/$listId'
    | '/_authenticated/app/new-job/$'
    | '/_authenticated/app/new-list/$'
    | '/api/public/hooks/records-inbound'
    | '/api/public/hooks/telnyx-call'
    | '/api/public/hooks/telnyx-dlr'
    | '/api/public/hooks/telnyx-inbound'
    | '/api/public/hooks/tick-campaigns'
    | '/api/public/hooks/tick-distress-feed'
    | '/api/public/hooks/tick-jobs'
    | '/api/public/hooks/tick-realeflow-sourcing'
    | '/api/public/hooks/tick-records-requests'
    | '/api/public/hooks/tick-registrations'
    | '/api/public/hooks/tick-sequences'
    | '/api/public/hooks/tick-template-health'
    | '/api/public/hub/callback'
    | '/api/public/v1/campaigns'
    | '/api/public/v1/jobs'
    | '/api/public/v1/leads'
    | '/distress-feed/counties/$state/$county'
    | '/_authenticated/app/campaigns/'
    | '/_authenticated/app/jobs/'
    | '/_authenticated/app/lists/'
    | '/_authenticated/app/new-job/'
    | '/_authenticated/app/new-list/'
    | '/distress-feed/counties/$state/'
    | '/distress-feed/guides/$state/'
    | '/api/public/v1/jobs/$jobId'
    | '/distress-feed/guides/$state/$county/$recordType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AgencyRoute: typeof AgencyRoute
  AiDrivingForDollarsRoute: typeof AiDrivingForDollarsRoute
  AuthRoute: typeof AuthRouteWithChildren
  AutoRoute: typeof AutoRoute
  B2bRoute: typeof B2bRoute
  ComplianceRoute: typeof ComplianceRoute
  EcommerceRoute: typeof EcommerceRoute
  EducationRoute: typeof EducationRoute
  FeaturesRoute: typeof FeaturesRoute
  HelpRoute: typeof HelpRoute
  HomeServicesRoute: typeof HomeServicesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IndustriesRoute: typeof IndustriesRoute
  InsuranceRoute: typeof InsuranceRoute
  LegalRoute: typeof LegalRoute
  MedicalRoute: typeof MedicalRoute
  MortgageRoute: typeof MortgageRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  RealestateRoute: typeof RealestateRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolarRoute: typeof SolarRoute
  StartRoute: typeof StartRoute
  StreetScanRoute: typeof StreetScanRoute
  TutorialsRoute: typeof TutorialsRoute
  LeadsSlugRoute: typeof LeadsSlugRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  ToolsDncCheckerRoute: typeof ToolsDncCheckerRoute
  ToolsLineTypeCheckerRoute: typeof ToolsLineTypeCheckerRoute
  DistressFeedIndexRoute: typeof DistressFeedIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  DistressFeedCountiesIndexRoute: typeof DistressFeedCountiesIndexRoute
  DistressFeedGuidesIndexRoute: typeof DistressFeedGuidesIndexRoute
  ApiPublicHooksRecordsInboundRoute: typeof ApiPublicHooksRecordsInboundRoute
  ApiPublicHooksTelnyxCallRoute: typeof ApiPublicHooksTelnyxCallRoute
  ApiPublicHooksTelnyxDlrRoute: typeof ApiPublicHooksTelnyxDlrRoute
  ApiPublicHooksTelnyxInboundRoute: typeof ApiPublicHooksTelnyxInboundRoute
  ApiPublicHooksTickCampaignsRoute: typeof ApiPublicHooksTickCampaignsRoute
  ApiPublicHooksTickDistressFeedRoute: typeof ApiPublicHooksTickDistressFeedRoute
  ApiPublicHooksTickJobsRoute: typeof ApiPublicHooksTickJobsRoute
  ApiPublicHooksTickRealeflowSourcingRoute: typeof ApiPublicHooksTickRealeflowSourcingRoute
  ApiPublicHooksTickRecordsRequestsRoute: typeof ApiPublicHooksTickRecordsRequestsRoute
  ApiPublicHooksTickRegistrationsRoute: typeof ApiPublicHooksTickRegistrationsRoute
  ApiPublicHooksTickSequencesRoute: typeof ApiPublicHooksTickSequencesRoute
  ApiPublicHooksTickTemplateHealthRoute: typeof ApiPublicHooksTickTemplateHealthRoute
  ApiPublicHubCallbackRoute: typeof ApiPublicHubCallbackRoute
  ApiPublicV1CampaignsRoute: typeof ApiPublicV1CampaignsRoute
  ApiPublicV1JobsRoute: typeof ApiPublicV1JobsRouteWithChildren
  ApiPublicV1LeadsRoute: typeof ApiPublicV1LeadsRoute
  DistressFeedCountiesStateCountyRoute: typeof DistressFeedCountiesStateCountyRoute
  DistressFeedCountiesStateIndexRoute: typeof DistressFeedCountiesStateIndexRoute
  DistressFeedGuidesStateIndexRoute: typeof DistressFeedGuidesStateIndexRoute
  DistressFeedGuidesStateCountyRecordTypeRoute: typeof DistressFeedGuidesStateCountyRecordTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/street-scan': {
      id: '/street-scan'
      path: '/street-scan'
      fullPath: '/street-scan'
      preLoaderRoute: typeof StreetScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar': {
      id: '/solar'
      path: '/solar'
      fullPath: '/solar'
      preLoaderRoute: typeof SolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realestate': {
      id: '/realestate'
      path: '/realestate'
      fullPath: '/realestate'
      preLoaderRoute: typeof RealestateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage': {
      id: '/mortgage'
      path: '/mortgage'
      fullPath: '/mortgage'
      preLoaderRoute: typeof MortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical': {
      id: '/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof MedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-services': {
      id: '/home-services'
      path: '/home-services'
      fullPath: '/home-services'
      preLoaderRoute: typeof HomeServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto': {
      id: '/auto'
      path: '/auto'
      fullPath: '/auto'
      preLoaderRoute: typeof AutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-driving-for-dollars': {
      id: '/ai-driving-for-dollars'
      path: '/ai-driving-for-dollars'
      fullPath: '/ai-driving-for-dollars'
      preLoaderRoute: typeof AiDrivingForDollarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distress-feed/': {
      id: '/distress-feed/'
      path: '/distress-feed'
      fullPath: '/distress-feed/'
      preLoaderRoute: typeof DistressFeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/line-type-checker': {
      id: '/tools/line-type-checker'
      path: '/tools/line-type-checker'
      fullPath: '/tools/line-type-checker'
      preLoaderRoute: typeof ToolsLineTypeCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/dnc-checker': {
      id: '/tools/dnc-checker'
      path: '/tools/dnc-checker'
      fullPath: '/tools/dnc-checker'
      preLoaderRoute: typeof ToolsDncCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$slug': {
      id: '/leads/$slug'
      path: '/leads/$slug'
      fullPath: '/leads/$slug'
      preLoaderRoute: typeof LeadsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/hub': {
      id: '/auth/hub'
      path: '/hub'
      fullPath: '/auth/hub'
      preLoaderRoute: typeof AuthHubRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/distress-feed/guides/': {
      id: '/distress-feed/guides/'
      path: '/distress-feed/guides'
      fullPath: '/distress-feed/guides/'
      preLoaderRoute: typeof DistressFeedGuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distress-feed/counties/': {
      id: '/distress-feed/counties/'
      path: '/distress-feed/counties'
      fullPath: '/distress-feed/counties/'
      preLoaderRoute: typeof DistressFeedCountiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/platform/workspaces': {
      id: '/_authenticated/platform/workspaces'
      path: '/workspaces'
      fullPath: '/platform/workspaces'
      preLoaderRoute: typeof AuthenticatedPlatformWorkspacesRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/sources': {
      id: '/_authenticated/platform/sources'
      path: '/sources'
      fullPath: '/platform/sources'
      preLoaderRoute: typeof AuthenticatedPlatformSourcesRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/sequences': {
      id: '/_authenticated/platform/sequences'
      path: '/sequences'
      fullPath: '/platform/sequences'
      preLoaderRoute: typeof AuthenticatedPlatformSequencesRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/records': {
      id: '/_authenticated/platform/records'
      path: '/records'
      fullPath: '/platform/records'
      preLoaderRoute: typeof AuthenticatedPlatformRecordsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/access': {
      id: '/_authenticated/platform/access'
      path: '/access'
      fullPath: '/platform/access'
      preLoaderRoute: typeof AuthenticatedPlatformAccessRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/app/workspace': {
      id: '/_authenticated/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/templates': {
      id: '/_authenticated/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AuthenticatedAppTemplatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/registration': {
      id: '/_authenticated/app/registration'
      path: '/registration'
      fullPath: '/app/registration'
      preLoaderRoute: typeof AuthenticatedAppRegistrationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/property-search': {
      id: '/_authenticated/app/property-search'
      path: '/property-search'
      fullPath: '/app/property-search'
      preLoaderRoute: typeof AuthenticatedAppPropertySearchRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/numbers': {
      id: '/_authenticated/app/numbers'
      path: '/numbers'
      fullPath: '/app/numbers'
      preLoaderRoute: typeof AuthenticatedAppNumbersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads': {
      id: '/_authenticated/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AuthenticatedAppLeadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/integrations': {
      id: '/_authenticated/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inbox': {
      id: '/_authenticated/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AuthenticatedAppInboxRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/compliance': {
      id: '/_authenticated/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AuthenticatedAppComplianceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/brands': {
      id: '/_authenticated/app/brands'
      path: '/brands'
      fullPath: '/app/brands'
      preLoaderRoute: typeof AuthenticatedAppBrandsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assistant': {
      id: '/_authenticated/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AuthenticatedAppAssistantRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/api': {
      id: '/_authenticated/app/api'
      path: '/api'
      fullPath: '/app/api'
      preLoaderRoute: typeof AuthenticatedAppApiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agent': {
      id: '/_authenticated/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AuthenticatedAppAgentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/distress-feed/guides/$state/': {
      id: '/distress-feed/guides/$state/'
      path: '/distress-feed/guides/$state'
      fullPath: '/distress-feed/guides/$state/'
      preLoaderRoute: typeof DistressFeedGuidesStateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distress-feed/counties/$state/': {
      id: '/distress-feed/counties/$state/'
      path: '/distress-feed/counties/$state'
      fullPath: '/distress-feed/counties/$state/'
      preLoaderRoute: typeof DistressFeedCountiesStateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/new-list/': {
      id: '/_authenticated/app/new-list/'
      path: '/new-list'
      fullPath: '/app/new-list/'
      preLoaderRoute: typeof AuthenticatedAppNewListIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/new-job/': {
      id: '/_authenticated/app/new-job/'
      path: '/new-job'
      fullPath: '/app/new-job/'
      preLoaderRoute: typeof AuthenticatedAppNewJobIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/lists/': {
      id: '/_authenticated/app/lists/'
      path: '/lists'
      fullPath: '/app/lists/'
      preLoaderRoute: typeof AuthenticatedAppListsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/jobs/': {
      id: '/_authenticated/app/jobs/'
      path: '/jobs'
      fullPath: '/app/jobs/'
      preLoaderRoute: typeof AuthenticatedAppJobsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns/': {
      id: '/_authenticated/app/campaigns/'
      path: '/campaigns'
      fullPath: '/app/campaigns/'
      preLoaderRoute: typeof AuthenticatedAppCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/distress-feed/counties/$state/$county': {
      id: '/distress-feed/counties/$state/$county'
      path: '/distress-feed/counties/$state/$county'
      fullPath: '/distress-feed/counties/$state/$county'
      preLoaderRoute: typeof DistressFeedCountiesStateCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/leads': {
      id: '/api/public/v1/leads'
      path: '/api/public/v1/leads'
      fullPath: '/api/public/v1/leads'
      preLoaderRoute: typeof ApiPublicV1LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/jobs': {
      id: '/api/public/v1/jobs'
      path: '/api/public/v1/jobs'
      fullPath: '/api/public/v1/jobs'
      preLoaderRoute: typeof ApiPublicV1JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/campaigns': {
      id: '/api/public/v1/campaigns'
      path: '/api/public/v1/campaigns'
      fullPath: '/api/public/v1/campaigns'
      preLoaderRoute: typeof ApiPublicV1CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hub/callback': {
      id: '/api/public/hub/callback'
      path: '/api/public/hub/callback'
      fullPath: '/api/public/hub/callback'
      preLoaderRoute: typeof ApiPublicHubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tick-template-health': {
      id: '/api/public/hooks/tick-template-health'
      path: '/api/public/hooks/tick-template-health'
      fullPath: '/api/public/hooks/tick-template-health'
      preLoaderRoute: typeof ApiPublicHooksTickTemplateHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tick-sequences': {
      id: '/api/public/hooks/tick-sequences'
      path: '/api/public/hooks/tick-sequences'
      fullPath: '/api/public/hooks/tick-sequences'
      preLoaderRoute: typeof ApiPublicHooksTickSequencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tick-registrations': {
      id: '/api/public/hooks/tick-registrations'
      path: '/api/public/hooks/tick-registrations'
      fullPath: '/api/public/hooks/tick-registrations'
      preLoaderRoute: typeof ApiPublicHooksTickRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tick-records-requests': {
      id: '/api/public/hooks/tick-records-requests'
      path: '/api/public/hooks/tick-records-requests'
      fullPath: '/api/public/hooks/tick-records-requests'
      preLoaderRoute: typeof ApiPublicHooksTickRecordsRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tick-realeflow-sourcing': {
      id: '/api/public/hooks/tick-realeflow-sourcing'
      path: '/api/public/hooks/tick-realeflow-sourcing'
      fullPath: '/api/public/hooks/tick-realeflow-sourcing'
      preLoaderRoute: typeof ApiPublicHooksTickRealeflowSourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tick-jobs': {
      id: '/api/public/hooks/tick-jobs'
      path: '/api/public/hooks/tick-jobs'
      fullPath: '/api/public/hooks/tick-jobs'
      preLoaderRoute: typeof ApiPublicHooksTickJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tick-distress-feed': {
      id: '/api/public/hooks/tick-distress-feed'
      path: '/api/public/hooks/tick-distress-feed'
      fullPath: '/api/public/hooks/tick-distress-feed'
      preLoaderRoute: typeof ApiPublicHooksTickDistressFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tick-campaigns': {
      id: '/api/public/hooks/tick-campaigns'
      path: '/api/public/hooks/tick-campaigns'
      fullPath: '/api/public/hooks/tick-campaigns'
      preLoaderRoute: typeof ApiPublicHooksTickCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telnyx-inbound': {
      id: '/api/public/hooks/telnyx-inbound'
      path: '/api/public/hooks/telnyx-inbound'
      fullPath: '/api/public/hooks/telnyx-inbound'
      preLoaderRoute: typeof ApiPublicHooksTelnyxInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telnyx-dlr': {
      id: '/api/public/hooks/telnyx-dlr'
      path: '/api/public/hooks/telnyx-dlr'
      fullPath: '/api/public/hooks/telnyx-dlr'
      preLoaderRoute: typeof ApiPublicHooksTelnyxDlrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telnyx-call': {
      id: '/api/public/hooks/telnyx-call'
      path: '/api/public/hooks/telnyx-call'
      fullPath: '/api/public/hooks/telnyx-call'
      preLoaderRoute: typeof ApiPublicHooksTelnyxCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/records-inbound': {
      id: '/api/public/hooks/records-inbound'
      path: '/api/public/hooks/records-inbound'
      fullPath: '/api/public/hooks/records-inbound'
      preLoaderRoute: typeof ApiPublicHooksRecordsInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/new-list/$': {
      id: '/_authenticated/app/new-list/$'
      path: '/new-list/$'
      fullPath: '/app/new-list/$'
      preLoaderRoute: typeof AuthenticatedAppNewListSplatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/new-job/$': {
      id: '/_authenticated/app/new-job/$'
      path: '/new-job/$'
      fullPath: '/app/new-job/$'
      preLoaderRoute: typeof AuthenticatedAppNewJobSplatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/lists/$listId': {
      id: '/_authenticated/app/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/app/lists/$listId'
      preLoaderRoute: typeof AuthenticatedAppListsListIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/jobs/$': {
      id: '/_authenticated/app/jobs/$'
      path: '/jobs/$'
      fullPath: '/app/jobs/$'
      preLoaderRoute: typeof AuthenticatedAppJobsSplatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns/new': {
      id: '/_authenticated/app/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/app/campaigns/new'
      preLoaderRoute: typeof AuthenticatedAppCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns/$campaignId': {
      id: '/_authenticated/app/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/app/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedAppCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/distress-feed/guides/$state/$county/$recordType': {
      id: '/distress-feed/guides/$state/$county/$recordType'
      path: '/distress-feed/guides/$state/$county/$recordType'
      fullPath: '/distress-feed/guides/$state/$county/$recordType'
      preLoaderRoute: typeof DistressFeedGuidesStateCountyRecordTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/jobs/$jobId': {
      id: '/api/public/v1/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/public/v1/jobs/$jobId'
      preLoaderRoute: typeof ApiPublicV1JobsJobIdRouteImport
      parentRoute: typeof ApiPublicV1JobsRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppAgentRoute: typeof AuthenticatedAppAgentRoute
  AuthenticatedAppApiRoute: typeof AuthenticatedAppApiRoute
  AuthenticatedAppAssistantRoute: typeof AuthenticatedAppAssistantRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppBrandsRoute: typeof AuthenticatedAppBrandsRoute
  AuthenticatedAppComplianceRoute: typeof AuthenticatedAppComplianceRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppInboxRoute: typeof AuthenticatedAppInboxRoute
  AuthenticatedAppIntegrationsRoute: typeof AuthenticatedAppIntegrationsRoute
  AuthenticatedAppLeadsRoute: typeof AuthenticatedAppLeadsRoute
  AuthenticatedAppNumbersRoute: typeof AuthenticatedAppNumbersRoute
  AuthenticatedAppPropertySearchRoute: typeof AuthenticatedAppPropertySearchRoute
  AuthenticatedAppRegistrationRoute: typeof AuthenticatedAppRegistrationRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppTemplatesRoute: typeof AuthenticatedAppTemplatesRoute
  AuthenticatedAppWorkspaceRoute: typeof AuthenticatedAppWorkspaceRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCampaignsCampaignIdRoute: typeof AuthenticatedAppCampaignsCampaignIdRoute
  AuthenticatedAppCampaignsNewRoute: typeof AuthenticatedAppCampaignsNewRoute
  AuthenticatedAppJobsSplatRoute: typeof AuthenticatedAppJobsSplatRoute
  AuthenticatedAppListsListIdRoute: typeof AuthenticatedAppListsListIdRoute
  AuthenticatedAppNewJobSplatRoute: typeof AuthenticatedAppNewJobSplatRoute
  AuthenticatedAppNewListSplatRoute: typeof AuthenticatedAppNewListSplatRoute
  AuthenticatedAppCampaignsIndexRoute: typeof AuthenticatedAppCampaignsIndexRoute
  AuthenticatedAppJobsIndexRoute: typeof AuthenticatedAppJobsIndexRoute
  AuthenticatedAppListsIndexRoute: typeof AuthenticatedAppListsIndexRoute
  AuthenticatedAppNewJobIndexRoute: typeof AuthenticatedAppNewJobIndexRoute
  AuthenticatedAppNewListIndexRoute: typeof AuthenticatedAppNewListIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppAgentRoute: AuthenticatedAppAgentRoute,
  AuthenticatedAppApiRoute: AuthenticatedAppApiRoute,
  AuthenticatedAppAssistantRoute: AuthenticatedAppAssistantRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppBrandsRoute: AuthenticatedAppBrandsRoute,
  AuthenticatedAppComplianceRoute: AuthenticatedAppComplianceRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppInboxRoute: AuthenticatedAppInboxRoute,
  AuthenticatedAppIntegrationsRoute: AuthenticatedAppIntegrationsRoute,
  AuthenticatedAppLeadsRoute: AuthenticatedAppLeadsRoute,
  AuthenticatedAppNumbersRoute: AuthenticatedAppNumbersRoute,
  AuthenticatedAppPropertySearchRoute: AuthenticatedAppPropertySearchRoute,
  AuthenticatedAppRegistrationRoute: AuthenticatedAppRegistrationRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppTemplatesRoute: AuthenticatedAppTemplatesRoute,
  AuthenticatedAppWorkspaceRoute: AuthenticatedAppWorkspaceRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCampaignsCampaignIdRoute:
    AuthenticatedAppCampaignsCampaignIdRoute,
  AuthenticatedAppCampaignsNewRoute: AuthenticatedAppCampaignsNewRoute,
  AuthenticatedAppJobsSplatRoute: AuthenticatedAppJobsSplatRoute,
  AuthenticatedAppListsListIdRoute: AuthenticatedAppListsListIdRoute,
  AuthenticatedAppNewJobSplatRoute: AuthenticatedAppNewJobSplatRoute,
  AuthenticatedAppNewListSplatRoute: AuthenticatedAppNewListSplatRoute,
  AuthenticatedAppCampaignsIndexRoute: AuthenticatedAppCampaignsIndexRoute,
  AuthenticatedAppJobsIndexRoute: AuthenticatedAppJobsIndexRoute,
  AuthenticatedAppListsIndexRoute: AuthenticatedAppListsIndexRoute,
  AuthenticatedAppNewJobIndexRoute: AuthenticatedAppNewJobIndexRoute,
  AuthenticatedAppNewListIndexRoute: AuthenticatedAppNewListIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedPlatformRouteChildren {
  AuthenticatedPlatformAccessRoute: typeof AuthenticatedPlatformAccessRoute
  AuthenticatedPlatformRecordsRoute: typeof AuthenticatedPlatformRecordsRoute
  AuthenticatedPlatformSequencesRoute: typeof AuthenticatedPlatformSequencesRoute
  AuthenticatedPlatformSourcesRoute: typeof AuthenticatedPlatformSourcesRoute
  AuthenticatedPlatformWorkspacesRoute: typeof AuthenticatedPlatformWorkspacesRoute
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
}

const AuthenticatedPlatformRouteChildren: AuthenticatedPlatformRouteChildren = {
  AuthenticatedPlatformAccessRoute: AuthenticatedPlatformAccessRoute,
  AuthenticatedPlatformRecordsRoute: AuthenticatedPlatformRecordsRoute,
  AuthenticatedPlatformSequencesRoute: AuthenticatedPlatformSequencesRoute,
  AuthenticatedPlatformSourcesRoute: AuthenticatedPlatformSourcesRoute,
  AuthenticatedPlatformWorkspacesRoute: AuthenticatedPlatformWorkspacesRoute,
  AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
}

const AuthenticatedPlatformRouteWithChildren =
  AuthenticatedPlatformRoute._addFileChildren(
    AuthenticatedPlatformRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthHubRoute: typeof AuthHubRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthHubRoute: AuthHubRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiPublicV1JobsRouteChildren {
  ApiPublicV1JobsJobIdRoute: typeof ApiPublicV1JobsJobIdRoute
}

const ApiPublicV1JobsRouteChildren: ApiPublicV1JobsRouteChildren = {
  ApiPublicV1JobsJobIdRoute: ApiPublicV1JobsJobIdRoute,
}

const ApiPublicV1JobsRouteWithChildren = ApiPublicV1JobsRoute._addFileChildren(
  ApiPublicV1JobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AgencyRoute: AgencyRoute,
  AiDrivingForDollarsRoute: AiDrivingForDollarsRoute,
  AuthRoute: AuthRouteWithChildren,
  AutoRoute: AutoRoute,
  B2bRoute: B2bRoute,
  ComplianceRoute: ComplianceRoute,
  EcommerceRoute: EcommerceRoute,
  EducationRoute: EducationRoute,
  FeaturesRoute: FeaturesRoute,
  HelpRoute: HelpRoute,
  HomeServicesRoute: HomeServicesRoute,
  HowItWorksRoute: HowItWorksRoute,
  IndustriesRoute: IndustriesRoute,
  InsuranceRoute: InsuranceRoute,
  LegalRoute: LegalRoute,
  MedicalRoute: MedicalRoute,
  MortgageRoute: MortgageRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  RealestateRoute: RealestateRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolarRoute: SolarRoute,
  StartRoute: StartRoute,
  StreetScanRoute: StreetScanRoute,
  TutorialsRoute: TutorialsRoute,
  LeadsSlugRoute: LeadsSlugRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  ToolsDncCheckerRoute: ToolsDncCheckerRoute,
  ToolsLineTypeCheckerRoute: ToolsLineTypeCheckerRoute,
  DistressFeedIndexRoute: DistressFeedIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  DistressFeedCountiesIndexRoute: DistressFeedCountiesIndexRoute,
  DistressFeedGuidesIndexRoute: DistressFeedGuidesIndexRoute,
  ApiPublicHooksRecordsInboundRoute: ApiPublicHooksRecordsInboundRoute,
  ApiPublicHooksTelnyxCallRoute: ApiPublicHooksTelnyxCallRoute,
  ApiPublicHooksTelnyxDlrRoute: ApiPublicHooksTelnyxDlrRoute,
  ApiPublicHooksTelnyxInboundRoute: ApiPublicHooksTelnyxInboundRoute,
  ApiPublicHooksTickCampaignsRoute: ApiPublicHooksTickCampaignsRoute,
  ApiPublicHooksTickDistressFeedRoute: ApiPublicHooksTickDistressFeedRoute,
  ApiPublicHooksTickJobsRoute: ApiPublicHooksTickJobsRoute,
  ApiPublicHooksTickRealeflowSourcingRoute:
    ApiPublicHooksTickRealeflowSourcingRoute,
  ApiPublicHooksTickRecordsRequestsRoute:
    ApiPublicHooksTickRecordsRequestsRoute,
  ApiPublicHooksTickRegistrationsRoute: ApiPublicHooksTickRegistrationsRoute,
  ApiPublicHooksTickSequencesRoute: ApiPublicHooksTickSequencesRoute,
  ApiPublicHooksTickTemplateHealthRoute: ApiPublicHooksTickTemplateHealthRoute,
  ApiPublicHubCallbackRoute: ApiPublicHubCallbackRoute,
  ApiPublicV1CampaignsRoute: ApiPublicV1CampaignsRoute,
  ApiPublicV1JobsRoute: ApiPublicV1JobsRouteWithChildren,
  ApiPublicV1LeadsRoute: ApiPublicV1LeadsRoute,
  DistressFeedCountiesStateCountyRoute: DistressFeedCountiesStateCountyRoute,
  DistressFeedCountiesStateIndexRoute: DistressFeedCountiesStateIndexRoute,
  DistressFeedGuidesStateIndexRoute: DistressFeedGuidesStateIndexRoute,
  DistressFeedGuidesStateCountyRecordTypeRoute:
    DistressFeedGuidesStateCountyRecordTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
